spring:
  application:
    name: pageablebooks

  datasource:
    url: jdbc:h2:mem:books
    driver-class-name: org.h2.Driver
    username: books
    password: books

  h2:
    console:
      enabled: true